bkdosen/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index');


Route::get('/modulVerif', 'modul_rencanaController@index2');

Route::resource('modulRencanas', 'modul_rencanaController');

Route::resource('users', 'usersController');

Route::get('/verifikasi/{id_rencana}', 'modul_rencanaController@verifikasi');


Route::resource('tahunAjars', 'tahun_ajarController');

Route::resource('realisasis', 'realisasiController');

Route::post('/ubah_file', 'realisasiController@ubah_file');

bkdosen/app/Models/tahun_ajar.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class tahun_ajar
 * @package App\Models
 * @version May 10, 2019, 2:50 am UTC
 *
 * @property string tahun_ajar
 */
class tahun_ajar extends Model
{
    use SoftDeletes;

    public $table = 'tahun_ajars';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'tahun_ajar'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'tahun_ajar' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'tahun_ajar' => 'required'
    ];

    
}

bkdosen/app/Http/Controllers/tahun_ajarController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Createtahun_ajarRequest;
use App\Http\Requests\Updatetahun_ajarRequest;
use App\Repositories\tahun_ajarRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class tahun_ajarController extends AppBaseController
{
    /** @var  tahun_ajarRepository */
    private $tahunAjarRepository;

    public function __construct(tahun_ajarRepository $tahunAjarRepo)
    {
        $this->tahunAjarRepository = $tahunAjarRepo;
    }

    /**
     * Display a listing of the tahun_ajar.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->tahunAjarRepository->pushCriteria(new RequestCriteria($request));
        $tahunAjars = $this->tahunAjarRepository->all();

        return view('tahun_ajars.index')
            ->with('tahunAjars', $tahunAjars);
    }

    /**
     * Show the form for creating a new tahun_ajar.
     *
     * @return Response
     */
    public function create()
    {
        return view('tahun_ajars.create');
    }

    /**
     * Store a newly created tahun_ajar in storage.
     *
     * @param Createtahun_ajarRequest $request
     *
     * @return Response
     */
    public function store(Createtahun_ajarRequest $request)
    {
        $input = $request->all();

        $tahunAjar = $this->tahunAjarRepository->create($input);

        Flash::success('Tahun Ajar saved successfully.');

        return redirect(route('tahunAjars.index'));
    }

    /**
     * Display the specified tahun_ajar.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $tahunAjar = $this->tahunAjarRepository->findWithoutFail($id);

        if (empty($tahunAjar)) {
            Flash::error('Tahun Ajar not found');

            return redirect(route('tahunAjars.index'));
        }

        return view('tahun_ajars.show')->with('tahunAjar', $tahunAjar);
    }

    /**
     * Show the form for editing the specified tahun_ajar.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $tahunAjar = $this->tahunAjarRepository->findWithoutFail($id);

        if (empty($tahunAjar)) {
            Flash::error('Tahun Ajar not found');

            return redirect(route('tahunAjars.index'));
        }

        return view('tahun_ajars.edit')->with('tahunAjar', $tahunAjar);
    }

    /**
     * Update the specified tahun_ajar in storage.
     *
     * @param  int              $id
     * @param Updatetahun_ajarRequest $request
     *
     * @return Response
     */
    public function update($id, Updatetahun_ajarRequest $request)
    {
        $tahunAjar = $this->tahunAjarRepository->findWithoutFail($id);

        if (empty($tahunAjar)) {
            Flash::error('Tahun Ajar not found');

            return redirect(route('tahunAjars.index'));
        }

        $tahunAjar = $this->tahunAjarRepository->update($request->all(), $id);

        Flash::success('Tahun Ajar updated successfully.');

        return redirect(route('tahunAjars.index'));
    }

    /**
     * Remove the specified tahun_ajar from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $tahunAjar = $this->tahunAjarRepository->findWithoutFail($id);

        if (empty($tahunAjar)) {
            Flash::error('Tahun Ajar not found');

            return redirect(route('tahunAjars.index'));
        }

        $this->tahunAjarRepository->delete($id);

        Flash::success('Tahun Ajar deleted successfully.');

        return redirect(route('tahunAjars.index'));
    }
}

bkdosen/resources/views/tahun_ajars/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Tahun Ajar
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'tahunAjars.store']) !!}

                        @include('tahun_ajars.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

bkdosen/resources/views/tahun_ajars/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Tahun Ajar
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($tahunAjar, ['route' => ['tahunAjars.update', $tahunAjar->id], 'method' => 'patch']) !!}

                        @include('tahun_ajars.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

bkdosen/resources/views/tahun_ajars/fields.blade.php
<div class="form-group col-sm-6">
    {!! Form::label('tahun_ajar', 'tahun ajar:') !!}
    {!! Form::text('tahun_ajar', null , ['class' => 'form-control']) !!}
 
</div>
<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('tahunAjars.index') !!}" class="btn btn-default">Cancel</a>
</div>

bkdosen/resources/views/tahun_ajars/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Tahun Ajars</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('tahunAjars.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('tahun_ajars.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

bkdosen/resources/views/tahun_ajars/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Tahun Ajar
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('tahun_ajars.show_fields')
                    <a href="{!! route('tahunAjars.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

bkdosen/resources/views/tahun_ajars/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $tahunAjar->id !!}</p>
</div>

<!-- Tahun Ajar Field -->
<div class="form-group">
    {!! Form::label('tahun_ajar', 'Tahun Ajar:') !!}
    <p>{!! $tahunAjar->tahun_ajar !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $tahunAjar->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $tahunAjar->updated_at !!}</p>
</div>

bkdosen/resources/views/tahun_ajars/table.blade.php
<table class="table table-responsive" id="tahunAjars-table">
    <thead>
        <tr>
            <th>Tahun Ajar</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($tahunAjars as $tahunAjar)
        <tr>
            <td>{!! $tahunAjar->tahun_ajar !!}</td>
            <td>
                {!! Form::open(['route' => ['tahunAjars.destroy', $tahunAjar->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('tahunAjars.show', [$tahunAjar->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('tahunAjars.edit', [$tahunAjar->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>