bkdosen/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index');


Route::get('/modulVerif', 'modul_rencanaController@index2');

Route::resource('modulRencanas', 'modul_rencanaController');

Route::resource('users', 'usersController');

Route::get('/verifikasi/{id_rencana}', 'modul_rencanaController@verifikasi');


Route::resource('tahunAjars', 'tahun_ajarController');

Route::resource('realisasis', 'realisasiController');

Route::post('/ubah_file', 'realisasiController@ubah_file');

bkdosen/app/Models/modul_rencana.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;


/**
 * Class modul_rencana
 * @package App\Models
 * @version March 7, 2019, 10:39 am UTC
 *
 * @property enum bidang
 * @property string kegiatan
 * @property string sks
 * @property string keterangan
 */
class modul_rencana extends Model
{
    use SoftDeletes;

    public $table = 'modul_rencanas';
    

    protected $dates = ['deleted_at'];


    public $fillable = [

        'NIK',
        'tahun_ajar',
        'prodi_fk',
        'bidang',
        'sub_bidang',
        'nama_kegiatan',
        'rencana_sks',
        'keterangan',
        'status'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [

        'NIK' => 'string',
        'tahun_ajar' => 'string',
        'prodi_fk' => 'sting',
        'bidang' => 'string',
        'sub_bidang' => 'string',
        'nama_kegiatan' => 'string',
        'rencana_sks' => 'string',
        'keterangan' => 'string',
        'status' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

        'NIK' => 'required',
        'tahun_ajar' => 'required',
        'prodi_fk' => 'required',
        'bidang' => 'required',
        'sub_bidang' => 'required',
        'nama_kegiatan' => 'required',
        'rencana_sks' => 'numeric',
        'keterangan' => '',
        'status' => 'required'
    ];

    public function realisasi(){
    	return $this->hasMany('\App\Models\realisasi','id_rencana_fk');
    }
    
    
}

bkdosen/app/Http/Controllers/modul_rencanaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Createmodul_rencanaRequest;
use App\Http\Requests\Updatemodul_rencanaRequest;
use App\Repositories\modul_rencanaRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
use DB;

class modul_rencanaController extends AppBaseController
{
    /** @var  modul_rencanaRepository */
    private $modulRencanaRepository;

    public function __construct(modul_rencanaRepository $modulRencanaRepo)
    {
        $this->modulRencanaRepository = $modulRencanaRepo;
    }

    /**
     * Display a listing of the modul_rencana.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->modulRencanaRepository->pushCriteria(new RequestCriteria($request));
        $modulRencanas = \App\Models\modul_rencana::where('NIK', '=', \Auth::user()->NIK)->get();
        
        return view('modul_rencanas.index')
            ->with('modulRencanas', $modulRencanas);
    }

    public function index2(Request $request)
    {
        $this->modulRencanaRepository->pushCriteria(new RequestCriteria($request));
        $modulRencanas = \App\Models\modul_rencana::where('prodi_fk', '=', \Auth::user()->prodi)->get();

        return view('modul_rencanas.index2')
            ->with('modulRencanas', $modulRencanas);
    }
    /**
     * Show the form for creating a new modul_rencana.
     *
     * @return Response
     */
    public function create()
    {   
        $tahun_ajar = DB::table('tahun_ajars')->pluck('tahun_ajar','tahun_ajar');

        return view('modul_rencanas.create', compact('tahun_ajar','tahun_ajar'));
    }

    /**
     * Store a newly created modul_rencana in storage.
     *
     * @param Createmodul_rencanaRequest $request
     *
     * @return Response
     */
    public function store(Createmodul_rencanaRequest $request)
    {
        $input = $request->all();

        $modulRencana = $this->modulRencanaRepository->create($input);

        Flash::success('Modul Rencana saved successfully.');

        return redirect(route('modulRencanas.index'));
    }

    /**
     * Display the specified modul_rencana.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $modulRencana = $this->modulRencanaRepository->findWithoutFail($id);

        if (empty($modulRencana)) {
            Flash::error('Modul Rencana not found');

            return redirect(route('modulRencanas.index'));
        }

        return view('modul_rencanas.show')->with('modulRencana', $modulRencana);
    }

    /**
     * Show the form for editing the specified modul_rencana.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $modulRencana = $this->modulRencanaRepository->findWithoutFail($id);

        $tahun_ajar = DB::table('tahun_ajars')->pluck('tahun_ajar','tahun_ajar');


        if (empty($modulRencana)) {

          
            Flash::error('Modul Rencana not found');

            return redirect(route('modulRencanas.index'));
        }

        return view('modul_rencanas.edit',  compact('tahun_ajar','tahun_ajar'))->with('modulRencana', $modulRencana);

    }

    /**
     * Update the specified modul_rencana in storage.
     *
     * @param  int              $id
     * @param Updatemodul_rencanaRequest $request
     *
     * @return Response
     */
    public function update($id, Updatemodul_rencanaRequest $request)
    {
        $modulRencana = $this->modulRencanaRepository->findWithoutFail($id);

        if (empty($modulRencana)) {
            Flash::error('Modul Rencana not found');

            return redirect(route('modulRencanas.index'));
        }

        $modulRencana = $this->modulRencanaRepository->update($request->all(), $id);

        Flash::success('Modul Rencana updated successfully.');

        return redirect(route('modulRencanas.index'));
    }

    /**
     * Remove the specified modul_rencana from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $modulRencana = $this->modulRencanaRepository->findWithoutFail($id);

        if (empty($modulRencana)) {
            Flash::error('Modul Rencana not found');

            return redirect(route('modulRencanas.index'));
        }

        $this->modulRencanaRepository->delete($id);

        Flash::success('Modul Rencana deleted successfully.');

        return redirect(route('modulRencanas.index'));
    }
    public function verifikasi($id){

        DB::table('modul_rencanas')
            ->where('id', $id)
            ->update(['status' => "Verified"]);
            return redirect('/modulVerif');
    }
}

bkdosen/resources/views/modul_rencanas/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Modul Rencana
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'modulRencanas.store']) !!}

                        @include('modul_rencanas.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

bkdosen/resources/views/modul_rencanas/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Modul Rencana
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($modulRencana, ['route' => ['modulRencanas.update', $modulRencana->id], 'method' => 'patch']) !!}

                        @include('modul_rencanas.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

bkdosen/resources/views/modul_rencanas/fields.blade.php
<!-- Bidang Field -->
<div class="form-group col-sm-6">
    {!! Form::label('NIK', 'NIK:') !!}
    {!! Form::text('NIK', Auth::user()->NIK , ['class' => 'form-control']) !!}
 
</div>

<div class="form-group col-sm-6">
    {!! Form::label('Prodi', 'Prodi:') !!}
    {!! Form::text('prodi_fk', Auth::user()->prodi , ['class' => 'form-control']) !!}
 
</div>


<!-- Tahun Ajar Field -->
<div class="form-group col-sm-6">
    {!! Form::label('tahun_ajar', 'Tahun Ajar:') !!}
    {!! Form::select('tahun_ajar', $tahun_ajar , null,  ['class' => 'form-control']) !!}
</div>


      
<!-- Bidang Field -->
<div class="col-md-6 col-sm-6" style="margin-bottom:15px;">
{!! Form::label('bidang', 'Bidang:') !!}
<select class="form-control" id="bidang" name="bidang">
<option value="">Pilih Bidang</option>
<option value="Pendidikan/Pengajar">Pendidikan/Pengajar</option>
<option value="BidangPeneltian">Bidang Penelitian</option>
<option value="BidangPengmas">Bidang Pengabdian pada Masyarakat</option>
<option value="BidangPenunjang">Bidang Penunjang</option>
</select>
</div>
<!-- Sub Bidang Field -->
<div class="col-md-6 col-sm-6">
{!! Form::label('sub_bidang', 'Sub Bidang:') !!}
<select class="form-control" id="sub_bidang" name="sub_bidang">
<option value="">Pilih Sub Bidang</option>
<option value="Pendidikan/Pengajar" data-chained="Pendidikan/Pengajar">Perkuliahan</option>
<option value="Praktikum" data-chained="Pendidikan/Pengajar">Praktikum</option>
<option value="Bimbingan Praktek Kerja/Magang" data-chained="Pendidikan/Pengajar">Bimbingan Praktek Kerja/Magang</option>
<option value="Seminar Terjadwal/Seminar KP" data-chained="Pendidikan/Pengajar">Seminar Terjadwal/Seminar KP</option>
<option value="Bimbingan Tugas Akhir/Skripsi/PKM" data-chained="Pendidikan/Pengajar">Bimbingan Tugas Akhir/Skripsi/PKM</option>
<option value="Menguji Tugas Akhir/Skripsi" data-chained="Pendidikan/Pengajar">Menguji Tugas Akhir/Skripsi</option>
<option value="Menguji Proposal Skripsi" data-chained="Pendidikan/Pengajar">Menguji Proposal Skripsi</option>
<option value="Membimbing Dosen Muda" data-chained="Pendidikan/Pengajar">Membimbing Dosen Muda</option>
<option value="Datasering/pencangkokan dosen" data-chained="Pendidikan/Pengajar">Datasering/pencangkokan dosen</option>
<option value="Mengembangkan Program Pengajaran" data-chained="Pendidikan/Pengajar">Mengembangkan Program Pengajaran</option>

<option value="Melakukan Penelitian Kelompok" data-chained="BidangPeneltian">Melakukan Penelitian Kelompok</option>
<option value="Melakukan Penelitian Mandiri" data-chained="BidangPeneltian">Melakukan Penelitian Mandiri</option>
<option value="Menulis Buku" data-chained="BidangPeneltian">Menulis Buku</option>
<option value="Menterjemahkan Buku" data-chained="BidangPeneltian">Menterjemahkan Buku</option>
<option value="Menyunting Buku" data-chained="BidangPeneltian">Menyunting Buku</option>
<option value="Menulis Diktat/Modul" data-chained="BidangPeneltian">Menulis Diktat/Modul</option>
<option value="Sebagai Asesor BKD" data-chained="BidangPeneltian">Sebagai Asesor BKD</option>
<option value="Menulis Jurnal Ilmiah/Poster/Proceeding" data-chained="BidangPeneltian">Menulis Jurnal Ilmiah/Poster/Proceeding</option>
<option value="Memperoleh Hak Paten" data-chained="BidangPeneltian">Memperoleh Hak Paten</option>
<option value="Menulis di Media Massa sesuai bidang" data-chained="BidangPeneltian">Menulis di Media Massa sesuai bidang</option>
<option value="Menyampaikan Orasi Ilmiah" data-chained="BidangPeneltian">Menyampaikan Orasi Ilmiah</option>
<option value="Penyaji Makalah dalam Seminar" data-chained="BidangPeneltian">Penyaji Makalah dalam Seminar</option>

<option value="Kegiatan Pengabdian pada Masyarakat" data-chained="BidangPengmas">Kegiatan Pengabdian pada Masyarakat</option>
<option value="Memberikan penyuluhan/penataran/ konsultansi pada masyarakat" data-chained="BidangPengmas">Memberikan penyuluhan/penataran/ konsultansi pada masyarakat</option>
<option value="Memberikan jasa konsultansi sebagai tenaga ahli" data-chained="BidangPengmas">Memberikan jasa konsultansi sebagai tenaga ahli</option>
<option value="Membuat karya pengabdian masyarakat yang digunakan untuk siswa SMA/umum" data-chained="BidangPengmas">Membuat karya pengabdian masyarakat yang digunakan untuk siswa SMA/umum</option>
<option value="Membuat karya pengabdian masyarakat sebagai modul/panduan yang digunakan oleh mahasiswa" data-chained="BidangPengmas">Membuat karya pengmas sebagai modul yang digunakan oleh mahasiswa</option>

<option value="Pembimbingan Akademik bagi Mahasiswa" data-chained="BidangPenunjang">Pembimbingan Akademik bagi Mahasiswa</option>
<option value="Bimbingan dan Konseling" data-chained="BidangPenunjang">Bimbingan dan Konseling</option>
<option value="Pembina unit kegiatan mahasiswa" data-chained="BidangPenunjang">Pembina unit kegiatan mahasiswa</option>
<option value="Jabatan Struktural/Non Struktural" data-chained="BidangPenunjang">Jabatan Struktural/Non Struktural</option>
<option value="Redaksi Jurnal ber-ISSN" data-chained="BidangPenunjang">Redaksi Jurnal ber-ISSN</option>
<option value="Panitia AdHoc/Panitia Tetap" data-chained="BidangPenunjang">Panitia AdHoc/Panitia Tetap</option>
<option value="Pengurus/Anggota Asosiasi Profesi" data-chained="BidangPenunjang">Pengurus/Anggota Asosiasi Profesi</option>
<option value="Peserta/juri/moderator dalam seminar/workshop/pelatihan" data-chained="BidangPenunjang">Peserta/juri/moderator dalam seminar/workshop/pelatihan</option>
<option value="Reviewer Jurnal/Proposal/Buku" data-chained="BidangPenunjang">Reviewer Jurnal/Proposal/Buku</option>
<option value="Kegiatan internal UPJ" data-chained="BidangPenunjang">Kegiatan internal UPJ</option>
</select>
</div>


<!-- Nama Kegiatan Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nama_kegiatan', 'Nama Kegiatan:') !!}
    {!! Form::text('nama_kegiatan', null, ['class' => 'form-control']) !!}
</div>

<!-- Rencana Sks Field -->
<div class="form-group col-sm-6">
    {!! Form::label('rencana_sks', 'Rencana Sks:') !!}
    {!! Form::number('rencana_sks', null, ['class' => 'form-control']) !!}
</div>

<!-- Keterangan Field -->
<div class="form-group col-sm-6">
    {!! Form::label('keterangan', 'Keterangan:') !!}
    {!! Form::text('keterangan', null, ['class' => 'form-control']) !!}
</div>
<!-- Status Field -->
<div class="form-group col-sm-6">
        {!!  Form::hidden('status', 'Not Verified') !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('modulRencanas.index') !!}" class="btn btn-default">Cancel</a>
</div>

bkdosen/resources/views/modul_rencanas/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Modul Rencana</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('modulRencanas.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('modul_rencanas.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

bkdosen/resources/views/modul_rencanas/index2.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Verifikasi Modul Rencana</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('modulRencanas.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('modul_rencanas.table2')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

bkdosen/resources/views/modul_rencanas/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Modul Rencana
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('modul_rencanas.show_fields')
                    <a href="{!! route('modulRencanas.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

bkdosen/resources/views/modul_rencanas/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $modulRencana->id !!}</p>
</div>

<!-- Bidang Field -->
<div class="form-group">
    {!! Form::label('bidang', 'Bidang:') !!}
    <p>{!! $modulRencana->bidang !!}</p>
</div>

<!-- Kegiatan Field -->
<div class="form-group">
    {!! Form::label('kegiatan', 'Kegiatan:') !!}
    <p>{!! $modulRencana->nama_kegiatan !!}</p>
</div>

<!-- Sks Field -->
<div class="form-group">
    {!! Form::label('sks', 'Sks:') !!}
    <p>{!! $modulRencana->rencana_sks !!}</p>
</div>

<!-- Keterangan Field -->
<div class="form-group">
    {!! Form::label('keterangan', 'Keterangan:') !!}
    <p>{!! $modulRencana->keterangan !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $modulRencana->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $modulRencana->updated_at !!}</p>
</div>

bkdosen/resources/views/modul_rencanas/table.blade.php
<table class="table table-responsive" id="modulRencanas-table">
    <thead>
        <tr>
            <th>Tahun Ajar</th>
            <th>Bidang</th>
            <th>Sub Bidang</th>
            <th>Nama Kegiatan</th>
            <th>Rencana Sks</th>
            <th>Keterangan</th>
            <th>Status</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach($modulRencanas as $modulRencana)
        <tr>
            <td>{!! $modulRencana->tahun_ajar !!}</td>
            <td>{!! $modulRencana->bidang !!}</td>
            <td>{!! $modulRencana->sub_bidang !!}</td>
            <td>{!! $modulRencana->nama_kegiatan !!}</td>
            <td>{!! $modulRencana->rencana_sks !!}</td>
            <td>{!! $modulRencana->keterangan !!}</td>
            <td>{!! $modulRencana->status !!}</td>
            <td>
                {!! Form::open(['route' => ['modulRencanas.destroy', $modulRencana->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('modulRencanas.show', [$modulRencana->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('modulRencanas.edit', [$modulRencana->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>

                {!! Form::close() !!}
            </td>
        </tr>
        @endforeach
    </tbody>
</table>

bkdosen/resources/views/modul_rencanas/table2.blade.php
<table class="table table-responsive" id="modulRencanas-table">
    <thead>
        <tr>
            <th>NIK</th>
            <th>Tahun Ajar</th>
            <th>Bidang</th>
            <th>Sub Bidang</th>
            <th>Nama Kegiatan</th>
            <th>Rencana Sks</th>
            <th>Keterangan</th>
            <th>Status</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach($modulRencanas as $modulRencana)
        <tr>
            <td>{!! $modulRencana->NIK !!}</td>
            <td>{!! $modulRencana->tahun_ajar !!}</td>
            <td>{!! $modulRencana->bidang !!}</td>
            <td>{!! $modulRencana->sub_bidang !!}</td>
            <td>{!! $modulRencana->nama_kegiatan !!}</td>
            <td>{!! $modulRencana->rencana_sks !!}</td>
            <td>{!! $modulRencana->keterangan !!}</td>
            <td>{!! $modulRencana->status !!}</td>
            <td>
                {!! Form::open(['route' => ['modulRencanas.destroy', $modulRencana->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('modulRencanas.show', [$modulRencana->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                 <a href="/verifikasi/{{$modulRencana->id}}">
                    <?php if($modulRencana->status == 'Not Verified'){?>
                <div class="btn-group">
                    <input type="button" value="konfirmasi" class="btn btn-success btn-xs" name="konfirmasi">
                </div>
                <?php }?>
                </a>
                {!! Form::close() !!}
            </td>
        </tr>
        @endforeach
    </tbody>
</table>